apiVersion: v1
kind: Service
metadata:
  name: echoserver-svc
  labels:
    run: echoserver-svc
    tag: kiran
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
